application: codercolumbus
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /admin
  script: admin.py

- url: /admin/.*
  script: admin.py

