application: codercolumbus
version: 1
runtime: python27
api_version: 1
threadsafe: yes


skip_files:
- ^(.*/)?.*\.py[co]
- ^\.gitignore
- ^\.git/.*
- ^\.idea/.*

handlers:
- url: /.*
  script: runapp.app


